<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/csi/conversation.proto

namespace Ondewo\Csi\SipTrigger;

use UnexpectedValueException;

/**
 * Type of SIP trigger that can be executed during a conversation.
 *
 * Protobuf type <code>ondewo.csi.SipTrigger.SipTriggerType</code>
 */
class SipTriggerType
{
    /**
     * should never be used
     *
     * Generated from protobuf enum <code>UNSPECIFIED = 0;</code>
     */
    const UNSPECIFIED = 0;
    /**
     * hard hangup
     *
     * Generated from protobuf enum <code>HANGUP = 1;</code>
     */
    const HANGUP = 1;
    /**
     * handover to human
     *
     * Generated from protobuf enum <code>HUMAN_HANDOVER = 2;</code>
     */
    const HUMAN_HANDOVER = 2;
    /**
     * send now
     *
     * Generated from protobuf enum <code>SEND_NOW = 3;</code>
     */
    const SEND_NOW = 3;
    /**
     * pause
     *
     * Generated from protobuf enum <code>PAUSE = 4;</code>
     */
    const PAUSE = 4;
    /**
     * transfer
     *
     * Generated from protobuf enum <code>TRANSFER = 5;</code>
     */
    const TRANSFER = 5;
    /**
     * invite to conference call
     *
     * Generated from protobuf enum <code>INVITE = 6;</code>
     */
    const INVITE = 6;
    /**
     * play audio
     *
     * Generated from protobuf enum <code>PLAY_AUDIO = 7;</code>
     */
    const PLAY_AUDIO = 7;

    private static $valueToName = [
        self::UNSPECIFIED => 'UNSPECIFIED',
        self::HANGUP => 'HANGUP',
        self::HUMAN_HANDOVER => 'HUMAN_HANDOVER',
        self::SEND_NOW => 'SEND_NOW',
        self::PAUSE => 'PAUSE',
        self::TRANSFER => 'TRANSFER',
        self::INVITE => 'INVITE',
        self::PLAY_AUDIO => 'PLAY_AUDIO',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

