<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/csi/conversation.proto

namespace Ondewo\Csi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * <p>Per-call operator media control level, sent by ondewo-sip to <code>SetCallMediaControl</code> and pushed by the
 * server on the control stream (<code>ControlStreamResponse.media_control</code>).</p>
 * <p>It always carries the FULL effective level. It is independent of the bot's own mixer mute that ondewo-csi
 * requests from ondewo-sip with <code>SipMute</code> / <code>SipUnMute</code>.</p>
 *
 * Generated from protobuf message <code>ondewo.csi.CallMediaControlLevel</code>
 */
class CallMediaControlLevel extends \Google\Protobuf\Internal\Message
{
    /**
     * <p>If <code>true</code>, the bot is muted: no text-to-speech is synthesized for new responses (the NLU turn
     * still runs), the in-flight utterance is aborted and discarded (never resumed), and soft-timeout fillers,
     * re-prompts and <code>PLAY_AUDIO</code> triggers produce no audio.</p>
     *
     * Generated from protobuf field <code>bool bot_muted = 1;</code>
     */
    protected $bot_muted = false;
    /**
     * <p>If <code>true</code>, the bot stops listening: the caller audio sent to speech-to-text is replaced by muted
     * zero frames at the capture cadence (the stream stays open and its clock stays aligned with the call), S2T
     * responses are dropped before barge-in adjudication and before NLU, and the turn, soft and silence
     * timers are suspended (they restart from zero on resume). Blanked audio is never back-filled.</p>
     *
     * Generated from protobuf field <code>bool listening_paused = 2;</code>
     */
    protected $listening_paused = false;
    /**
     * <p>ondewo-sip's container-lifetime monotonic counter. Never reset per call. The server applies a level only
     * when this value is strictly greater than the last applied one.</p>
     *
     * Generated from protobuf field <code>uint64 generation = 3;</code>
     */
    protected $generation = 0;
    /**
     * <p>Bounded reason token for logs and telemetry: <code>operator</code>, <code>participant</code>,
     * <code>takeover</code> or <code>resync</code>.</p>
     *
     * Generated from protobuf field <code>string reason = 4;</code>
     */
    protected $reason = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $bot_muted
     *           <p>If <code>true</code>, the bot is muted: no text-to-speech is synthesized for new responses (the NLU turn
     *           still runs), the in-flight utterance is aborted and discarded (never resumed), and soft-timeout fillers,
     *           re-prompts and <code>PLAY_AUDIO</code> triggers produce no audio.</p>
     *     @type bool $listening_paused
     *           <p>If <code>true</code>, the bot stops listening: the caller audio sent to speech-to-text is replaced by muted
     *           zero frames at the capture cadence (the stream stays open and its clock stays aligned with the call), S2T
     *           responses are dropped before barge-in adjudication and before NLU, and the turn, soft and silence
     *           timers are suspended (they restart from zero on resume). Blanked audio is never back-filled.</p>
     *     @type int|string $generation
     *           <p>ondewo-sip's container-lifetime monotonic counter. Never reset per call. The server applies a level only
     *           when this value is strictly greater than the last applied one.</p>
     *     @type string $reason
     *           <p>Bounded reason token for logs and telemetry: <code>operator</code>, <code>participant</code>,
     *           <code>takeover</code> or <code>resync</code>.</p>
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Csi\Conversation::initOnce();
        parent::__construct($data);
    }

    /**
     * <p>If <code>true</code>, the bot is muted: no text-to-speech is synthesized for new responses (the NLU turn
     * still runs), the in-flight utterance is aborted and discarded (never resumed), and soft-timeout fillers,
     * re-prompts and <code>PLAY_AUDIO</code> triggers produce no audio.</p>
     *
     * Generated from protobuf field <code>bool bot_muted = 1;</code>
     * @return bool
     */
    public function getBotMuted()
    {
        return $this->bot_muted;
    }

    /**
     * <p>If <code>true</code>, the bot is muted: no text-to-speech is synthesized for new responses (the NLU turn
     * still runs), the in-flight utterance is aborted and discarded (never resumed), and soft-timeout fillers,
     * re-prompts and <code>PLAY_AUDIO</code> triggers produce no audio.</p>
     *
     * Generated from protobuf field <code>bool bot_muted = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setBotMuted($var)
    {
        GPBUtil::checkBool($var);
        $this->bot_muted = $var;

        return $this;
    }

    /**
     * <p>If <code>true</code>, the bot stops listening: the caller audio sent to speech-to-text is replaced by muted
     * zero frames at the capture cadence (the stream stays open and its clock stays aligned with the call), S2T
     * responses are dropped before barge-in adjudication and before NLU, and the turn, soft and silence
     * timers are suspended (they restart from zero on resume). Blanked audio is never back-filled.</p>
     *
     * Generated from protobuf field <code>bool listening_paused = 2;</code>
     * @return bool
     */
    public function getListeningPaused()
    {
        return $this->listening_paused;
    }

    /**
     * <p>If <code>true</code>, the bot stops listening: the caller audio sent to speech-to-text is replaced by muted
     * zero frames at the capture cadence (the stream stays open and its clock stays aligned with the call), S2T
     * responses are dropped before barge-in adjudication and before NLU, and the turn, soft and silence
     * timers are suspended (they restart from zero on resume). Blanked audio is never back-filled.</p>
     *
     * Generated from protobuf field <code>bool listening_paused = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setListeningPaused($var)
    {
        GPBUtil::checkBool($var);
        $this->listening_paused = $var;

        return $this;
    }

    /**
     * <p>ondewo-sip's container-lifetime monotonic counter. Never reset per call. The server applies a level only
     * when this value is strictly greater than the last applied one.</p>
     *
     * Generated from protobuf field <code>uint64 generation = 3;</code>
     * @return int|string
     */
    public function getGeneration()
    {
        return $this->generation;
    }

    /**
     * <p>ondewo-sip's container-lifetime monotonic counter. Never reset per call. The server applies a level only
     * when this value is strictly greater than the last applied one.</p>
     *
     * Generated from protobuf field <code>uint64 generation = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGeneration($var)
    {
        GPBUtil::checkUint64($var);
        $this->generation = $var;

        return $this;
    }

    /**
     * <p>Bounded reason token for logs and telemetry: <code>operator</code>, <code>participant</code>,
     * <code>takeover</code> or <code>resync</code>.</p>
     *
     * Generated from protobuf field <code>string reason = 4;</code>
     * @return string
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * <p>Bounded reason token for logs and telemetry: <code>operator</code>, <code>participant</code>,
     * <code>takeover</code> or <code>resync</code>.</p>
     *
     * Generated from protobuf field <code>string reason = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->reason = $var;

        return $this;
    }

}

