<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/csi/conversation.proto

namespace Ondewo\Csi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Health checks.
 *
 * Generated from protobuf message <code>ondewo.csi.CheckUpstreamHealthResponse</code>
 */
class CheckUpstreamHealthResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Health checks for Speech-2-Text
     *
     * Generated from protobuf field <code>.google.rpc.Status s2t_status = 1;</code>
     */
    protected $s2t_status = null;
    /**
     * Health checks for NLU
     *
     * Generated from protobuf field <code>.google.rpc.Status nlu_status = 2;</code>
     */
    protected $nlu_status = null;
    /**
     * Health checks for Text-2-Speech
     *
     * Generated from protobuf field <code>.google.rpc.Status t2s_status = 3;</code>
     */
    protected $t2s_status = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Rpc\Status $s2t_status
     *           Health checks for Speech-2-Text
     *     @type \Google\Rpc\Status $nlu_status
     *           Health checks for NLU
     *     @type \Google\Rpc\Status $t2s_status
     *           Health checks for Text-2-Speech
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Csi\Conversation::initOnce();
        parent::__construct($data);
    }

    /**
     * Health checks for Speech-2-Text
     *
     * Generated from protobuf field <code>.google.rpc.Status s2t_status = 1;</code>
     * @return \Google\Rpc\Status|null
     */
    public function getS2TStatus()
    {
        return $this->s2t_status;
    }

    public function hasS2TStatus()
    {
        return isset($this->s2t_status);
    }

    public function clearS2TStatus()
    {
        unset($this->s2t_status);
    }

    /**
     * Health checks for Speech-2-Text
     *
     * Generated from protobuf field <code>.google.rpc.Status s2t_status = 1;</code>
     * @param \Google\Rpc\Status $var
     * @return $this
     */
    public function setS2TStatus($var)
    {
        GPBUtil::checkMessage($var, \Google\Rpc\Status::class);
        $this->s2t_status = $var;

        return $this;
    }

    /**
     * Health checks for NLU
     *
     * Generated from protobuf field <code>.google.rpc.Status nlu_status = 2;</code>
     * @return \Google\Rpc\Status|null
     */
    public function getNluStatus()
    {
        return $this->nlu_status;
    }

    public function hasNluStatus()
    {
        return isset($this->nlu_status);
    }

    public function clearNluStatus()
    {
        unset($this->nlu_status);
    }

    /**
     * Health checks for NLU
     *
     * Generated from protobuf field <code>.google.rpc.Status nlu_status = 2;</code>
     * @param \Google\Rpc\Status $var
     * @return $this
     */
    public function setNluStatus($var)
    {
        GPBUtil::checkMessage($var, \Google\Rpc\Status::class);
        $this->nlu_status = $var;

        return $this;
    }

    /**
     * Health checks for Text-2-Speech
     *
     * Generated from protobuf field <code>.google.rpc.Status t2s_status = 3;</code>
     * @return \Google\Rpc\Status|null
     */
    public function getT2SStatus()
    {
        return $this->t2s_status;
    }

    public function hasT2SStatus()
    {
        return isset($this->t2s_status);
    }

    public function clearT2SStatus()
    {
        unset($this->t2s_status);
    }

    /**
     * Health checks for Text-2-Speech
     *
     * Generated from protobuf field <code>.google.rpc.Status t2s_status = 3;</code>
     * @param \Google\Rpc\Status $var
     * @return $this
     */
    public function setT2SStatus($var)
    {
        GPBUtil::checkMessage($var, \Google\Rpc\Status::class);
        $this->t2s_status = $var;

        return $this;
    }

}

