<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/csi/conversation.proto

namespace Ondewo\Csi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A condition message with its type and value.
 * A Condition can be of various types.
 * Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:
 * Immediate execution:
 * <pre><code>
 *{
 *    &quot;type&quot;: &quot;immediate&quot;
 *}
 *</code></pre>
 * Number of interactions of the user with the AI agent:
 * <pre><code>
 *{
 *    &quot;type&quot;: &quot;interactions&quot;,
 *    &quot;value&quot;: &quot;10&quot;
 *}
 *</code></pre>
 * Number of seconds:
 * <pre><code>
 *{
 *    &quot;type&quot;: &quot;duration&quot;,
 *    &quot;value&quot;: &quot;3600&quot;
 *}
 *</code></pre>
 * At a specific date and time:
 * <pre><code>
 *{
 *    &quot;type&quot;: &quot;datetime&quot;,
 *    &quot;value&quot;: &quot;2021-12-23T13:45:00.000Z&quot;
 *}
 *</code></pre>
 *
 * Generated from protobuf message <code>ondewo.csi.Condition</code>
 */
class Condition extends \Google\Protobuf\Internal\Message
{
    /**
     * Condition type
     *
     * Generated from protobuf field <code>.ondewo.csi.ConditionType type = 1;</code>
     */
    protected $type = 0;
    /**
     * Value of the condition. Examples of conditions values based on the condition type are given in the <code>ConditionType</code> documentation.
     *
     * Generated from protobuf field <code>string value = 2;</code>
     */
    protected $value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *           Condition type
     *     @type string $value
     *           Value of the condition. Examples of conditions values based on the condition type are given in the <code>ConditionType</code> documentation.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Csi\Conversation::initOnce();
        parent::__construct($data);
    }

    /**
     * Condition type
     *
     * Generated from protobuf field <code>.ondewo.csi.ConditionType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Condition type
     *
     * Generated from protobuf field <code>.ondewo.csi.ConditionType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Ondewo\Csi\ConditionType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Value of the condition. Examples of conditions values based on the condition type are given in the <code>ConditionType</code> documentation.
     *
     * Generated from protobuf field <code>string value = 2;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Value of the condition. Examples of conditions values based on the condition type are given in the <code>ConditionType</code> documentation.
     *
     * Generated from protobuf field <code>string value = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

}

