<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/csi/conversation.proto

namespace Ondewo\Csi;

use UnexpectedValueException;

/**
 * Type of condition that need to be satisfied to execute a control message.
 *
 * Protobuf type <code>ondewo.csi.ConditionType</code>
 */
class ConditionType
{
    /**
     * Unknown type
     *
     * Generated from protobuf enum <code>UNKNOWTYPE = 0;</code>
     */
    const UNKNOWTYPE = 0;
    /**
     * Immediate execution of the control message. Example value need be given as a string in the format: <pre><code>value=&quot;5&quot;</code></pre>
     *
     * Generated from protobuf enum <code>immediate = 1;</code>
     */
    const immediate = 1;
    /**
     * Duration in number of seconds after a control message should be executed. Example value need be given as a string in the format: <pre><code>value=&quot;10&quot;</code></pre>
     *
     * Generated from protobuf enum <code>duration = 2;</code>
     */
    const duration = 2;
    /**
     * Date and time when a control message should be executed. Example value need be given as a string in the format: <pre><code>value=&quot;2021-12-23T13:45:00.000Z&quot;</code></pre>
     *
     * Generated from protobuf enum <code>datetime = 3;</code>
     */
    const datetime = 3;
    /**
     * Number of interactions of the user with an ONDEWO AI agent after a control message should be executed. Example value need be given as a string in the format: <pre><code>value=&quot;4&quot;</code></pre>
     *
     * Generated from protobuf enum <code>interactions = 4;</code>
     */
    const interactions = 4;

    private static $valueToName = [
        self::UNKNOWTYPE => 'UNKNOWTYPE',
        self::immediate => 'immediate',
        self::duration => 'duration',
        self::datetime => 'datetime',
        self::interactions => 'interactions',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

