<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/csi/conversation.proto

namespace Ondewo\Csi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Control stream response message.
 *
 * Generated from protobuf message <code>ondewo.csi.ControlStreamResponse</code>
 */
class ControlStreamResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Control status
     *
     * Generated from protobuf field <code>.ondewo.csi.ControlStatus control_status = 1;</code>
     */
    protected $control_status = 0;
    /**
     * Monotonic barge-in epoch/sequence number so control status transitions are correlatable with the <code>S2sStreamResponse</code> <code>turn_epoch</code> and a second barge-in during a resumed remainder can never be coalesced away
     *
     * Generated from protobuf field <code>uint64 epoch = 2;</code>
     */
    protected $epoch = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $control_status
     *           Control status
     *     @type int|string $epoch
     *           Monotonic barge-in epoch/sequence number so control status transitions are correlatable with the <code>S2sStreamResponse</code> <code>turn_epoch</code> and a second barge-in during a resumed remainder can never be coalesced away
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Csi\Conversation::initOnce();
        parent::__construct($data);
    }

    /**
     * Control status
     *
     * Generated from protobuf field <code>.ondewo.csi.ControlStatus control_status = 1;</code>
     * @return int
     */
    public function getControlStatus()
    {
        return $this->control_status;
    }

    /**
     * Control status
     *
     * Generated from protobuf field <code>.ondewo.csi.ControlStatus control_status = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setControlStatus($var)
    {
        GPBUtil::checkEnum($var, \Ondewo\Csi\ControlStatus::class);
        $this->control_status = $var;

        return $this;
    }

    /**
     * Monotonic barge-in epoch/sequence number so control status transitions are correlatable with the <code>S2sStreamResponse</code> <code>turn_epoch</code> and a second barge-in during a resumed remainder can never be coalesced away
     *
     * Generated from protobuf field <code>uint64 epoch = 2;</code>
     * @return int|string
     */
    public function getEpoch()
    {
        return $this->epoch;
    }

    /**
     * Monotonic barge-in epoch/sequence number so control status transitions are correlatable with the <code>S2sStreamResponse</code> <code>turn_epoch</code> and a second barge-in during a resumed remainder can never be coalesced away
     *
     * Generated from protobuf field <code>uint64 epoch = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEpoch($var)
    {
        GPBUtil::checkUint64($var);
        $this->epoch = $var;

        return $this;
    }

}

