<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/csi/conversation.proto

namespace Ondewo\Csi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A control message.
 * Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:
 * <pre><code>
 *{
 *   &quot;service&quot;: &quot;&lt;SERVICE_NAME&gt;&quot;, 			// e.g. ondewo_s2t
 *   &quot;method&quot;: &quot;&lt;SERVICE_CONTROL_METHOD&gt;&quot;, 	// e.g. update_config
 *   &quot;parameters&quot;: [
 *       // primitive data types and JSON objects are possible
 *       1,
 *       1.0,
 *       -2.0,
 *       &quot;string&quot;,
 *       true,
 *   	 {
 *           // parameter JSON object
 *       },
 *       {
 *           // Condition start object
 *       },
 *       {
 *           // Condition end object [optional]
 *       },
 *    ]
 *}
 *</code></pre>
 *
 * Generated from protobuf message <code>ondewo.csi.ControlMessage</code>
 */
class ControlMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Service to control. Valid service names are: <code>ondewo_nlu</code>, <code>ondewo_t2s</code>, <code>ondewo_s2t</code>, <code>ondewo_sip</code> and <code>ondewo_csi</code>.
     *
     * Generated from protobuf field <code>.ondewo.csi.ControlMessageServiceName service = 1;</code>
     */
    protected $service = 0;
    /**
     * Method to invoke on the service
     *
     * Generated from protobuf field <code>.ondewo.csi.ControlMessageServiceMethod method = 2;</code>
     */
    protected $method = 0;
    /**
     * Parameters to use to invoke the method of the service
     *
     * Generated from protobuf field <code>.ondewo.csi.ControlMessageServiceParameters parameters = 3;</code>
     */
    protected $parameters = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $service
     *           Service to control. Valid service names are: <code>ondewo_nlu</code>, <code>ondewo_t2s</code>, <code>ondewo_s2t</code>, <code>ondewo_sip</code> and <code>ondewo_csi</code>.
     *     @type int $method
     *           Method to invoke on the service
     *     @type \Ondewo\Csi\ControlMessageServiceParameters $parameters
     *           Parameters to use to invoke the method of the service
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Csi\Conversation::initOnce();
        parent::__construct($data);
    }

    /**
     * Service to control. Valid service names are: <code>ondewo_nlu</code>, <code>ondewo_t2s</code>, <code>ondewo_s2t</code>, <code>ondewo_sip</code> and <code>ondewo_csi</code>.
     *
     * Generated from protobuf field <code>.ondewo.csi.ControlMessageServiceName service = 1;</code>
     * @return int
     */
    public function getService()
    {
        return $this->service;
    }

    /**
     * Service to control. Valid service names are: <code>ondewo_nlu</code>, <code>ondewo_t2s</code>, <code>ondewo_s2t</code>, <code>ondewo_sip</code> and <code>ondewo_csi</code>.
     *
     * Generated from protobuf field <code>.ondewo.csi.ControlMessageServiceName service = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setService($var)
    {
        GPBUtil::checkEnum($var, \Ondewo\Csi\ControlMessageServiceName::class);
        $this->service = $var;

        return $this;
    }

    /**
     * Method to invoke on the service
     *
     * Generated from protobuf field <code>.ondewo.csi.ControlMessageServiceMethod method = 2;</code>
     * @return int
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Method to invoke on the service
     *
     * Generated from protobuf field <code>.ondewo.csi.ControlMessageServiceMethod method = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkEnum($var, \Ondewo\Csi\ControlMessageServiceMethod::class);
        $this->method = $var;

        return $this;
    }

    /**
     * Parameters to use to invoke the method of the service
     *
     * Generated from protobuf field <code>.ondewo.csi.ControlMessageServiceParameters parameters = 3;</code>
     * @return \Ondewo\Csi\ControlMessageServiceParameters|null
     */
    public function getParameters()
    {
        return $this->parameters;
    }

    public function hasParameters()
    {
        return isset($this->parameters);
    }

    public function clearParameters()
    {
        unset($this->parameters);
    }

    /**
     * Parameters to use to invoke the method of the service
     *
     * Generated from protobuf field <code>.ondewo.csi.ControlMessageServiceParameters parameters = 3;</code>
     * @param \Ondewo\Csi\ControlMessageServiceParameters $var
     * @return $this
     */
    public function setParameters($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Csi\ControlMessageServiceParameters::class);
        $this->parameters = $var;

        return $this;
    }

}

