<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/csi/conversation.proto

namespace Ondewo\Csi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Parameters of the control message passed to the service specified in the control message.
 *
 * Generated from protobuf message <code>ondewo.csi.ControlMessageServiceParameters</code>
 */
class ControlMessageServiceParameters extends \Google\Protobuf\Internal\Message
{
    /**
     * SIP: callee id to transfer call to
     *
     * Generated from protobuf field <code>string transfer_id = 3;</code>
     */
    protected $transfer_id = '';
    /**
     * SIP: bytes of audio files to play to a caller
     *
     * Generated from protobuf field <code>repeated bytes wav_files = 4;</code>
     */
    private $wav_files;
    /**
     * text, e.g. for NLU detect intent response or Text-2-Speech voice synthesis
     *
     * Generated from protobuf field <code>string text = 5;</code>
     */
    protected $text = '';
    /**
     * NLU: context for creating, updating or deleting contextual information from a NLU session
     *
     * Generated from protobuf field <code>.ondewo.nlu.Context context = 6;</code>
     */
    protected $context = null;
    /**
     * NLU: the session id of a NLU session
     *
     * Generated from protobuf field <code>string session_id = 7;</code>
     */
    protected $session_id = '';
    /**
     * NLU: the name of the context of a NLU session
     *
     * Generated from protobuf field <code>string context_name = 8;</code>
     */
    protected $context_name = '';
    /**
     * CSI: the condition that defines when a control message should be executed
     *
     * Generated from protobuf field <code>.ondewo.csi.Condition condition_start = 9;</code>
     */
    protected $condition_start = null;
    /**
     * CSI: the condition that defines when a control message should stop its execution
     *
     * Generated from protobuf field <code>.ondewo.csi.Condition condition_end = 10;</code>
     */
    protected $condition_end = null;
    protected $config;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ondewo\T2s\RequestConfig $t2s_config
     *           Text-2-Speech: configuration to control the synthesis of a text into audio
     *     @type \Ondewo\S2t\TranscribeRequestConfig $s2t_config
     *           Speech-2-Text: configuration to control the recognition of text based on human voice audio
     *     @type string $transfer_id
     *           SIP: callee id to transfer call to
     *     @type string[] $wav_files
     *           SIP: bytes of audio files to play to a caller
     *     @type string $text
     *           text, e.g. for NLU detect intent response or Text-2-Speech voice synthesis
     *     @type \Ondewo\Nlu\Context $context
     *           NLU: context for creating, updating or deleting contextual information from a NLU session
     *     @type string $session_id
     *           NLU: the session id of a NLU session
     *     @type string $context_name
     *           NLU: the name of the context of a NLU session
     *     @type \Ondewo\Csi\Condition $condition_start
     *           CSI: the condition that defines when a control message should be executed
     *     @type \Ondewo\Csi\Condition $condition_end
     *           CSI: the condition that defines when a control message should stop its execution
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Csi\Conversation::initOnce();
        parent::__construct($data);
    }

    /**
     * Text-2-Speech: configuration to control the synthesis of a text into audio
     *
     * Generated from protobuf field <code>.ondewo.t2s.RequestConfig t2s_config = 1;</code>
     * @return \Ondewo\T2s\RequestConfig|null
     */
    public function getT2SConfig()
    {
        return $this->readOneof(1);
    }

    public function hasT2SConfig()
    {
        return $this->hasOneof(1);
    }

    /**
     * Text-2-Speech: configuration to control the synthesis of a text into audio
     *
     * Generated from protobuf field <code>.ondewo.t2s.RequestConfig t2s_config = 1;</code>
     * @param \Ondewo\T2s\RequestConfig $var
     * @return $this
     */
    public function setT2SConfig($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\T2s\RequestConfig::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Speech-2-Text: configuration to control the recognition of text based on human voice audio
     *
     * Generated from protobuf field <code>.ondewo.s2t.TranscribeRequestConfig s2t_config = 2;</code>
     * @return \Ondewo\S2t\TranscribeRequestConfig|null
     */
    public function getS2TConfig()
    {
        return $this->readOneof(2);
    }

    public function hasS2TConfig()
    {
        return $this->hasOneof(2);
    }

    /**
     * Speech-2-Text: configuration to control the recognition of text based on human voice audio
     *
     * Generated from protobuf field <code>.ondewo.s2t.TranscribeRequestConfig s2t_config = 2;</code>
     * @param \Ondewo\S2t\TranscribeRequestConfig $var
     * @return $this
     */
    public function setS2TConfig($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\S2t\TranscribeRequestConfig::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * SIP: callee id to transfer call to
     *
     * Generated from protobuf field <code>string transfer_id = 3;</code>
     * @return string
     */
    public function getTransferId()
    {
        return $this->transfer_id;
    }

    /**
     * SIP: callee id to transfer call to
     *
     * Generated from protobuf field <code>string transfer_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTransferId($var)
    {
        GPBUtil::checkString($var, True);
        $this->transfer_id = $var;

        return $this;
    }

    /**
     * SIP: bytes of audio files to play to a caller
     *
     * Generated from protobuf field <code>repeated bytes wav_files = 4;</code>
     * @return RepeatedField<string>
     */
    public function getWavFiles()
    {
        return $this->wav_files;
    }

    /**
     * SIP: bytes of audio files to play to a caller
     *
     * Generated from protobuf field <code>repeated bytes wav_files = 4;</code>
     * @param string[] $var
     * @return $this
     */
    public function setWavFiles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->wav_files = $arr;

        return $this;
    }

    /**
     * text, e.g. for NLU detect intent response or Text-2-Speech voice synthesis
     *
     * Generated from protobuf field <code>string text = 5;</code>
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * text, e.g. for NLU detect intent response or Text-2-Speech voice synthesis
     *
     * Generated from protobuf field <code>string text = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setText($var)
    {
        GPBUtil::checkString($var, True);
        $this->text = $var;

        return $this;
    }

    /**
     * NLU: context for creating, updating or deleting contextual information from a NLU session
     *
     * Generated from protobuf field <code>.ondewo.nlu.Context context = 6;</code>
     * @return \Ondewo\Nlu\Context|null
     */
    public function getContext()
    {
        return $this->context;
    }

    public function hasContext()
    {
        return isset($this->context);
    }

    public function clearContext()
    {
        unset($this->context);
    }

    /**
     * NLU: context for creating, updating or deleting contextual information from a NLU session
     *
     * Generated from protobuf field <code>.ondewo.nlu.Context context = 6;</code>
     * @param \Ondewo\Nlu\Context $var
     * @return $this
     */
    public function setContext($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Nlu\Context::class);
        $this->context = $var;

        return $this;
    }

    /**
     * NLU: the session id of a NLU session
     *
     * Generated from protobuf field <code>string session_id = 7;</code>
     * @return string
     */
    public function getSessionId()
    {
        return $this->session_id;
    }

    /**
     * NLU: the session id of a NLU session
     *
     * Generated from protobuf field <code>string session_id = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->session_id = $var;

        return $this;
    }

    /**
     * NLU: the name of the context of a NLU session
     *
     * Generated from protobuf field <code>string context_name = 8;</code>
     * @return string
     */
    public function getContextName()
    {
        return $this->context_name;
    }

    /**
     * NLU: the name of the context of a NLU session
     *
     * Generated from protobuf field <code>string context_name = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setContextName($var)
    {
        GPBUtil::checkString($var, True);
        $this->context_name = $var;

        return $this;
    }

    /**
     * CSI: the condition that defines when a control message should be executed
     *
     * Generated from protobuf field <code>.ondewo.csi.Condition condition_start = 9;</code>
     * @return \Ondewo\Csi\Condition|null
     */
    public function getConditionStart()
    {
        return $this->condition_start;
    }

    public function hasConditionStart()
    {
        return isset($this->condition_start);
    }

    public function clearConditionStart()
    {
        unset($this->condition_start);
    }

    /**
     * CSI: the condition that defines when a control message should be executed
     *
     * Generated from protobuf field <code>.ondewo.csi.Condition condition_start = 9;</code>
     * @param \Ondewo\Csi\Condition $var
     * @return $this
     */
    public function setConditionStart($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Csi\Condition::class);
        $this->condition_start = $var;

        return $this;
    }

    /**
     * CSI: the condition that defines when a control message should stop its execution
     *
     * Generated from protobuf field <code>.ondewo.csi.Condition condition_end = 10;</code>
     * @return \Ondewo\Csi\Condition|null
     */
    public function getConditionEnd()
    {
        return $this->condition_end;
    }

    public function hasConditionEnd()
    {
        return isset($this->condition_end);
    }

    public function clearConditionEnd()
    {
        unset($this->condition_end);
    }

    /**
     * CSI: the condition that defines when a control message should stop its execution
     *
     * Generated from protobuf field <code>.ondewo.csi.Condition condition_end = 10;</code>
     * @param \Ondewo\Csi\Condition $var
     * @return $this
     */
    public function setConditionEnd($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Csi\Condition::class);
        $this->condition_end = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getConfig()
    {
        return $this->whichOneof("config");
    }

}

