<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/csi/conversation.proto

namespace Ondewo\Csi;

use UnexpectedValueException;

/**
 * Control status.
 *
 * Protobuf type <code>ondewo.csi.ControlStatus</code>
 */
class ControlStatus
{
    /**
     * Status that control stream is ok
     *
     * Generated from protobuf enum <code>OK = 0;</code>
     */
    const OK = 0;
    /**
     * Status that control stream needs to stop immediately
     *
     * Generated from protobuf enum <code>EMERGENCY_STOP = 1;</code>
     */
    const EMERGENCY_STOP = 1;
    /**
     * Status that voice activity detection detected start of speech
     *
     * Generated from protobuf enum <code>VAD_START_OF_SPEECH = 2;</code>
     */
    const VAD_START_OF_SPEECH = 2;
    /**
     * Status that the caller started speaking while the bot was speaking (barge-in): playback pauses and the un-played audio remainder is buffered
     *
     * Generated from protobuf enum <code>BARGE_IN = 3;</code>
     */
    const BARGE_IN = 3;
    /**
     * Status sent by the server to the client to resume playback of the buffered audio remainder after a false interruption (no committed transcription final arrived within the false interruption timeout)
     *
     * Generated from protobuf enum <code>RESUME_PLAYBACK = 4;</code>
     */
    const RESUME_PLAYBACK = 4;
    /**
     * Status sent by the server to the client to discard the buffered audio remainder because the interruption committed as a real turn
     *
     * Generated from protobuf enum <code>DISCARD_REMAINDER = 5;</code>
     */
    const DISCARD_REMAINDER = 5;
    /**
     * Status reported by the client to the server via <code>SetControlStatus</code> that playback of the buffered audio remainder has resumed
     *
     * Generated from protobuf enum <code>PLAYBACK_RESUMED = 6;</code>
     */
    const PLAYBACK_RESUMED = 6;
    /**
     * Status reported by the client to the server via <code>SetControlStatus</code> that playback of an utterance has completed
     *
     * Generated from protobuf enum <code>PLAYBACK_DONE = 7;</code>
     */
    const PLAYBACK_DONE = 7;
    /**
     * Status reported by ondewo-sip to the server via <code>SetControlStatus</code> that the phone call has ENDED and the server must reset ALL per-call state in place (persistent-listener model). It is a command, not a state: it is never pushed onto the control stream
     *
     * Generated from protobuf enum <code>CALL_ENDED = 8;</code>
     */
    const CALL_ENDED = 8;

    private static $valueToName = [
        self::OK => 'OK',
        self::EMERGENCY_STOP => 'EMERGENCY_STOP',
        self::VAD_START_OF_SPEECH => 'VAD_START_OF_SPEECH',
        self::BARGE_IN => 'BARGE_IN',
        self::RESUME_PLAYBACK => 'RESUME_PLAYBACK',
        self::DISCARD_REMAINDER => 'DISCARD_REMAINDER',
        self::PLAYBACK_RESUMED => 'PLAYBACK_RESUMED',
        self::PLAYBACK_DONE => 'PLAYBACK_DONE',
        self::CALL_ENDED => 'CALL_ENDED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

