<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/csi/conversation.proto

namespace Ondewo\Csi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Control stream response message.
 *
 * Generated from protobuf message <code>ondewo.csi.ControlStreamResponse</code>
 */
class ControlStreamResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Control status
     *
     * Generated from protobuf field <code>.ondewo.csi.ControlStatus control_status = 1;</code>
     */
    protected $control_status = 0;
    /**
     * Monotonic barge-in epoch/sequence number so control status transitions are correlatable with the <code>S2sStreamResponse</code> <code>turn_epoch</code> and a second barge-in during a resumed remainder can never be coalesced away
     *
     * Generated from protobuf field <code>uint64 epoch = 2;</code>
     */
    protected $epoch = 0;
    /**
     * <p>Optional. The per-call operator media control level. Set ONLY on media-control messages: pushed when the
     * level changes (<code>SetCallMediaControl</code>) and sent as the seed on every <code>GetControlStream</code>
     * connect.</p>
     * <p>A message that has this field set is a media-control message and nothing else: a client must handle it
     * and must NOT read its <code>control_status</code> / <code>epoch</code> as a control status transition. The
     * server echoes the current control status and epoch in it, but a client that applied that
     * <code>control_status</code> (e.g. <code>OK</code>) would un-latch a pending <code>BARGE_IN</code>.
     * Messages without this field keep their meaning unchanged.</p>
     *
     * Generated from protobuf field <code>.ondewo.csi.CallMediaControlLevel media_control = 3;</code>
     */
    protected $media_control = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $control_status
     *           Control status
     *     @type int|string $epoch
     *           Monotonic barge-in epoch/sequence number so control status transitions are correlatable with the <code>S2sStreamResponse</code> <code>turn_epoch</code> and a second barge-in during a resumed remainder can never be coalesced away
     *     @type \Ondewo\Csi\CallMediaControlLevel $media_control
     *           <p>Optional. The per-call operator media control level. Set ONLY on media-control messages: pushed when the
     *           level changes (<code>SetCallMediaControl</code>) and sent as the seed on every <code>GetControlStream</code>
     *           connect.</p>
     *           <p>A message that has this field set is a media-control message and nothing else: a client must handle it
     *           and must NOT read its <code>control_status</code> / <code>epoch</code> as a control status transition. The
     *           server echoes the current control status and epoch in it, but a client that applied that
     *           <code>control_status</code> (e.g. <code>OK</code>) would un-latch a pending <code>BARGE_IN</code>.
     *           Messages without this field keep their meaning unchanged.</p>
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Csi\Conversation::initOnce();
        parent::__construct($data);
    }

    /**
     * Control status
     *
     * Generated from protobuf field <code>.ondewo.csi.ControlStatus control_status = 1;</code>
     * @return int
     */
    public function getControlStatus()
    {
        return $this->control_status;
    }

    /**
     * Control status
     *
     * Generated from protobuf field <code>.ondewo.csi.ControlStatus control_status = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setControlStatus($var)
    {
        GPBUtil::checkEnum($var, \Ondewo\Csi\ControlStatus::class);
        $this->control_status = $var;

        return $this;
    }

    /**
     * Monotonic barge-in epoch/sequence number so control status transitions are correlatable with the <code>S2sStreamResponse</code> <code>turn_epoch</code> and a second barge-in during a resumed remainder can never be coalesced away
     *
     * Generated from protobuf field <code>uint64 epoch = 2;</code>
     * @return int|string
     */
    public function getEpoch()
    {
        return $this->epoch;
    }

    /**
     * Monotonic barge-in epoch/sequence number so control status transitions are correlatable with the <code>S2sStreamResponse</code> <code>turn_epoch</code> and a second barge-in during a resumed remainder can never be coalesced away
     *
     * Generated from protobuf field <code>uint64 epoch = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEpoch($var)
    {
        GPBUtil::checkUint64($var);
        $this->epoch = $var;

        return $this;
    }

    /**
     * <p>Optional. The per-call operator media control level. Set ONLY on media-control messages: pushed when the
     * level changes (<code>SetCallMediaControl</code>) and sent as the seed on every <code>GetControlStream</code>
     * connect.</p>
     * <p>A message that has this field set is a media-control message and nothing else: a client must handle it
     * and must NOT read its <code>control_status</code> / <code>epoch</code> as a control status transition. The
     * server echoes the current control status and epoch in it, but a client that applied that
     * <code>control_status</code> (e.g. <code>OK</code>) would un-latch a pending <code>BARGE_IN</code>.
     * Messages without this field keep their meaning unchanged.</p>
     *
     * Generated from protobuf field <code>.ondewo.csi.CallMediaControlLevel media_control = 3;</code>
     * @return \Ondewo\Csi\CallMediaControlLevel|null
     */
    public function getMediaControl()
    {
        return $this->media_control;
    }

    public function hasMediaControl()
    {
        return isset($this->media_control);
    }

    public function clearMediaControl()
    {
        unset($this->media_control);
    }

    /**
     * <p>Optional. The per-call operator media control level. Set ONLY on media-control messages: pushed when the
     * level changes (<code>SetCallMediaControl</code>) and sent as the seed on every <code>GetControlStream</code>
     * connect.</p>
     * <p>A message that has this field set is a media-control message and nothing else: a client must handle it
     * and must NOT read its <code>control_status</code> / <code>epoch</code> as a control status transition. The
     * server echoes the current control status and epoch in it, but a client that applied that
     * <code>control_status</code> (e.g. <code>OK</code>) would un-latch a pending <code>BARGE_IN</code>.
     * Messages without this field keep their meaning unchanged.</p>
     *
     * Generated from protobuf field <code>.ondewo.csi.CallMediaControlLevel media_control = 3;</code>
     * @param \Ondewo\Csi\CallMediaControlLevel $var
     * @return $this
     */
    public function setMediaControl($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Csi\CallMediaControlLevel::class);
        $this->media_control = $var;

        return $this;
    }

}

