<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/csi/conversation.proto

namespace Ondewo\Csi;

use UnexpectedValueException;

/**
 * Control message methods to control services during a conversation.
 *
 * Protobuf type <code>ondewo.csi.ControlMessageServiceMethod</code>
 */
class ControlMessageServiceMethod
{
    /**
     * Unknown method (default)
     *
     * Generated from protobuf enum <code>UNKNOWNMETHOD = 0;</code>
     */
    const UNKNOWNMETHOD = 0;
    /**
     * CSI: update configuration
     * <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
     * <pre><code>
     *{
     *    &quot;service&quot;: &quot;ondewo_s2t&quot;,
     *    &quot;method&quot;: &quot;update_config&quot;,
     *    &quot;parameters&quot;: [
     *        {
     *            // Speech2TextConfig object
     *            &quot;s2tPipelineId&quot; : &quot;s2t_pipeline_german_1&quot;,
     *            &quot;languageModelName&quot; : &quot;language_model_german&quot;
     *        },
     *        {
     *             // condition_start object =&gt; should take effect immediately
     *             &quot;type&quot;: &quot;immediate&quot;,
     *             &quot;value&quot;: &quot;0&quot;
     *        },
     *        {
     *             // condition_end object - s2t config will be changed back to
     *             // last valid configuration after 10 interactions of user with
     *             // the AI agent
     *             &quot;type&quot;: &quot;interactions&quot;,
     *	           &quot;value&quot;: 10
     *        },
     *    ]
     *}
     *</code></pre>
     *
     * Generated from protobuf enum <code>update_config = 1;</code>
     */
    const update_config = 1;
    /**
     * CSI: undo previous configuration update
     * <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
     * <pre><code>
     *{
     *    &quot;service&quot;: &quot;ondewo_s2t&quot;,
     *    &quot;method&quot;: &quot;undo_config&quot;,
     *    &quot;parameters&quot;: [
     *        {
     *	 	      // condition_start object
     *        },
     *        {
     *	 	      // condition_end object (OPTIONAL) - for permanent change
     *	          // no condition_end needs to be supplied i.e.
     *		      // this parameter is missing or empty &quot;{}&quot;
     *        },
     *    ]
     *}
     *</code></pre>
     *
     * Generated from protobuf enum <code>undo_config = 2;</code>
     */
    const undo_config = 2;
    /**
     * CSI: reset configuration to default
     * <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
     * <pre><code>
     *{
     *    &quot;service&quot;: &quot;ondewo_s2t&quot;,
     *    &quot;method&quot;: &quot;reset_config&quot;,
     *    &quot;parameters&quot;: [
     *        {
     *	 	      // condition_start object
     *        },
     *        {
     *	 	      // condition_end object (OPTIONAL) - for permanent change
     *            // no condition_end needs to be supplied i.e.
     *		      // this parameter is missing or empty &quot;{}&quot;
     *        },
     *    ]
     *}
     *</code></pre>
     *
     * Generated from protobuf enum <code>reset_config = 3;</code>
     */
    const reset_config = 3;
    /**
     * SIP: end conversation / hang up call
     * <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
     * <pre><code>
     *{
     *    &quot;service&quot;: &quot;ondewo_sip&quot;,
     *    &quot;method&quot;: &quot;end_call&quot;,
     *    &quot;parameters&quot;: [
     *        {
     *	 	      // condition_start object
     *        },
     *        {
     *	 	      // condition_end object (OPTIONAL) - for permanent change
     *            // no condition_end needs to be supplied i.e.
     *		      // this parameter is missing or empty &quot;{}&quot;
     *        },
     *    ]
     *}
     *</code></pre>
     *
     * Generated from protobuf enum <code>end_call = 4;</code>
     */
    const end_call = 4;
    /**
     * SIP: transfer call
     * <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
     * <pre><code>
     *{
     *    &quot;service&quot;: &quot;ondewo_sip&quot;,
     *    &quot;method&quot;: &quot;transfer_call&quot;,
     *    &quot;parameters&quot;: [
     *        {
     *	 	      &quot;transfer_id&quot;: &quot;+43123456789\@127.0.0.10:5060&quot;,
     *        },
     *        {
     *	 	      // condition_start object
     *        },
     *        {
     *	 	      // condition_end object (OPTIONAL) - for permanent change
     *            // no condition_end needs to be supplied i.e.
     *		      // this parameter is missing or empty &quot;{}&quot;
     *        },
     *    ]
     *}
     *</code></pre>
     *
     * Generated from protobuf enum <code>transfer_call = 5;</code>
     */
    const transfer_call = 5;
    /**
     * SIP: play wav files on the call
     * <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
     * <pre><code>
     *{
     *    &quot;service&quot;: &quot;ondewo_sip&quot;,
     *    &quot;method&quot;: &quot;play_wav_files&quot;,
     *    &quot;parameters&quot;: [
     *        {
     *	 	      &quot;wav_files&quot;:  [
     *                &lt;bytes_of_file_1&gt;,
     *                &lt;bytes_of_file_2&gt;,
     *                &lt;bytes_of_file_3&gt;,
     *            ]
     *        },
     *        {
     *	 	      // condition_start object
     *        },
     *        {
     *	 	      // condition_end object (OPTIONAL) - for permanent change
     *            // no condition_end needs to be supplied i.e.
     *		      // this parameter is missing or empty “{}”
     *        },
     *    ]
     *}
     *</code></pre>
     *
     * Generated from protobuf enum <code>play_wav_files = 6;</code>
     */
    const play_wav_files = 6;
    /**
     * SIP: play a certain text on the phone based on Text-2-Speech synthesis
     * <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
     * <pre><code>
     *{
     *    &quot;service&quot;: &quot;ondewo_sip&quot;,
     *    &quot;method&quot;: &quot;play_text&quot;,
     *    &quot;parameters&quot;: [
     *        {
     *	 	      &quot;text&quot;: &quot;Welcome from ONDEWO AI Agent! How are you today?&quot;,
     *        },
     *        {
     *	 	      // condition_start object
     *        },
     *        {
     *	 	      // condition_end object (OPTIONAL) - for permanent change
     *            // no condition_end needs to be supplied i.e.
     *		      // this parameter is missing or empty &quot;{}&quot;
     *        },
     *    ]
     *}
     *</code></pre>
     *
     * Generated from protobuf enum <code>play_text = 7;</code>
     */
    const play_text = 7;
    /**
     * SIP: mute microphone
     * <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
     * <pre><code>
     *{
     *    &quot;service&quot;: &quot;ondewo_sip&quot;,
     *    &quot;method&quot;: &quot;mute&quot;,
     *    &quot;parameters&quot;: [
     *        {
     *	 	      // condition_start object
     *        },
     *        {
     *	 	      // condition_end object (OPTIONAL) - for permanent change
     *            // no condition_end needs to be supplied i.e.
     *		      // this parameter is missing or empty &quot;{}&quot;
     *        },
     *    ]
     *}
     *</code></pre>
     *
     * Generated from protobuf enum <code>mute = 8;</code>
     */
    const mute = 8;
    /**
     * SIP: unmute microphone
     * <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
     * <pre><code>
     *{
     *    &quot;service&quot;: &quot;ondewo_sip&quot;,
     *    &quot;method&quot;: &quot;un_mute&quot;,
     *    &quot;parameters&quot;: [
     *        {
     *	 	      // condition_start object
     *        },
     *        {
     *	 	      // condition_end object (OPTIONAL) - for permanent change
     *            // no condition_end needs to be supplied i.e.
     *		      // this parameter is missing or empty &quot;{}&quot;
     *        },
     *    ]
     *}
     *</code></pre>
     *
     * Generated from protobuf enum <code>un_mute = 9;</code>
     */
    const un_mute = 9;
    /**
     * CSI: stop the execution of all running and scheduled control messages
     * <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
     * <pre><code>
     *{
     *    &quot;service&quot;: &quot;&quot;,    &lt;= empty string since it is for all services / no specific service
     *    &quot;method&quot;: &quot;stop_all_control_messages&quot;,
     *    "parameters": [
     *        {
     *	 	      // condition_start object
     *        },
     *        {
     *	 	      // condition_end object (OPTIONAL) - for permanent change
     *            // no condition_end needs to be supplied i.e.
     *		      // this parameter is missing or empty “{}”
     *        },
     *    ]
     *}
     *</code></pre>
     *
     * Generated from protobuf enum <code>stop_all_control_messages = 10;</code>
     */
    const stop_all_control_messages = 10;
    /**
     * NLU: train agent
     * <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
     * <pre><code>
     *{
     *    &quot;service&quot;: &quot;ondewo_nlu&quot;,
     *    &quot;method&quot;: &quot;train_agent&quot;,
     *    &quot;parameters&quot;: [
     *        {
     *	 	      // condition_start object
     *        },
     *        {
     *	 	      // condition_end object (OPTIONAL) - for permanent change
     *            // no condition_end needs to be supplied i.e.
     *		      // this parameter is missing or empty &quot;{}&quot;
     *        },
     *    ]
     *}
     *</code></pre>
     *
     * Generated from protobuf enum <code>train_agent = 11;</code>
     */
    const train_agent = 11;
    /**
     * NLU: cancel the ongoing agent
     * <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
     * <pre><code>
     *{
     *    &quot;service&quot;: &quot;ondewo_nlu&quot;,
     *    &quot;method&quot;: &quot;cancel_train_agent&quot;,
     *    &quot;parameters&quot;: [
     *        {
     *	 	      // condition_start object
     *        },
     *        {
     *	 	      // condition_end object (OPTIONAL) - for permanent change
     *            // no condition_end needs to be supplied i.e.
     *		      // this parameter is missing or empty &quot;{}&quot;
     *        },
     *    ]
     *}
     *</code></pre>
     *
     * Generated from protobuf enum <code>cancel_train_agent = 12;</code>
     */
    const cancel_train_agent = 12;
    /**
     * NLU: delete session and all session-related information
     * <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
     * <pre><code>
     *{
     *    &quot;service&quot;: &quot;ondewo_nlu&quot;,
     *    &quot;method&quot;: &quot;delete_session&quot;,
     *    &quot;parameters&quot;: [
     *        {
     *	 	      &quot;session_id&quot;: &quot;97ea1a20-0784-442b-93c0-eb9e2469420e&quot;,
     *        },
     *        {
     *	 	      // condition_start object
     *        },
     *        {
     *	 	      // condition_end object (OPTIONAL) - for permanent change
     *            // no condition_end needs to be supplied i.e.
     *		      // this parameter is missing or empty &quot;{}&quot;
     *        },
     *    ]
     *}
     *</code></pre>
     *
     * Generated from protobuf enum <code>delete_session = 13;</code>
     */
    const delete_session = 13;
    /**
     * NLU: delete all context information in the current session
     * <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
     * <pre><code>
     *{
     *    &quot;service&quot;: &quot;ondewo_nlu&quot;,
     *    &quot;method&quot;: &quot;delete_all_contexts&quot;,
     *    &quot;parameters&quot;: [
     *        {
     *	 	      &quot;session_id&quot;: &quot;97ea1a20-0784-442b-93c0-eb9e2469420e&quot;,
     *        },
     *        {
     *	 	      // condition_start object
     *        },
     *        {
     *	 	      // condition_end object (OPTIONAL) - for permanent change
     *            // no condition_end needs to be supplied i.e.
     *		      // this parameter is missing or empty &quot;{}&quot;
     *        },
     *    ]
     *}
     *</code></pre>
     *
     * Generated from protobuf enum <code>delete_all_contexts = 14;</code>
     */
    const delete_all_contexts = 14;
    /**
     * NLU: create a context based on the provided contextual information in the current session
     * <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
     * <pre><code>
     *{
     *    "service": "ondewo_nlu",
     *    "method": "create_context",
     *    "parameters": [
     *        {
     *	 	      &quot;context&quot;: {           &lt;== &lt;NLU Context Object as JSON object&gt;
     *                &quot;name&quot;: &quot;projects/db46dcf8-2d2c-4115-ac38-eff443ea0e72/agent/sessions/ss2ea1a20-0784-442b-93c0-eb9e2469420e/contexts/78ea1a20-0784-442b-93c0-eb9e2469420e&quot;,
     *                ...,
     *            }
     *        },
     *        {
     *	 	      // condition_start object
     *        },
     *        {
     *	 	      // condition_end object (OPTIONAL) - for permanent change
     *            // no condition_end needs to be supplied i.e.
     *		      // this parameter is missing or empty “{}”
     *        },
     *    ]
     *}
     *</code></pre>
     *
     * Generated from protobuf enum <code>create_context = 15;</code>
     */
    const create_context = 15;
    /**
     * NLU: update an existing context based on the provided contextual information in the current session
     * <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
     * <pre><code>
     *{
     *    "service": "ondewo_nlu",
     *    "method": "update_context",
     *    "parameters": [
     *        {
     *	 	      &quot;context&quot;: {           &lt;== &lt;NLU Context Object as JSON object&gt;
     *                &quot;name&quot;: &quot;projects/db46dcf8-2d2c-4115-ac38-eff443ea0e72/agent/sessions/2dea1a20-0784-442b-93c0-eb9e2469420e/contexts/78ea1a20-0784-442b-93c0-eb9e2469420e&quot;,
     *                ...,
     *            }
     *        },
     *        {
     *	 	      // condition_start object
     *        },
     *        {
     *	 	      // condition_end object (OPTIONAL) - for permanent change
     *            // no condition_end needs to be supplied i.e.
     *		      // this parameter is missing or empty “{}”
     *        },
     *    ]
     *}
     *</code></pre>
     *
     * Generated from protobuf enum <code>update_context = 16;</code>
     */
    const update_context = 16;
    /**
     * NLU: delete an existing context including all contextual information in the current session
     * <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
     * <pre><code>
     *{
     *    &quot;service&quot;: &quot;ondewo_nlu&quot;,
     *    &quot;method&quot;: &quot;delete_context&quot;,
     *    &quot;parameters&quot;: [
     *        {
     *	 	      &quot;session_id&quot;: &quot;97ea1a20-0784-442b-93c0-eb9e2469420e&quot;,
     *	 	      &quot;context_name&quot;: &quot;78ea1a20-0784-442b-93c0-eb9e2469420e&quot;,
     *        },
     *        {
     *	 	      // condition_start object
     *        },
     *        {
     *	 	      // condition_end object (OPTIONAL) - for permanent change
     *            // no condition_end needs to be supplied i.e.
     *		      // this parameter is missing or empty &quot;{}&quot;
     *        },
     *    ]
     *}
     *</code></pre>
     *
     * Generated from protobuf enum <code>delete_context = 17;</code>
     */
    const delete_context = 17;
    /**
     * NLU: execute a detect intent request based on the provided information in the current session
     * <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
     * <pre><code>
     *{
     *    &quot;service&quot;: &quot;ondewo_nlu&quot;,
     *    &quot;method&quot;: &quot;detect_intent&quot;,
     *    &quot;parameters&quot;: [
     *        {
     *	 	      &quot;session_id&quot;: &quot;97ea1a20-0784-442b-93c0-eb9e2469420e&quot;,
     *	 	      &quot;text&quot;: &quot;Are you an artificial intelligence?&quot;,
     *        },
     *        {
     *	 	      // condition_start object
     *        },
     *        {
     *	 	      // condition_end object (OPTIONAL) - for permanent change
     *            // no condition_end needs to be supplied i.e.
     *		      // this parameter is missing or empty &quot;{}&quot;
     *        },
     *    ]
     *}
     *</code></pre>
     *
     * Generated from protobuf enum <code>detect_intent = 18;</code>
     */
    const detect_intent = 18;

    private static $valueToName = [
        self::UNKNOWNMETHOD => 'UNKNOWNMETHOD',
        self::update_config => 'update_config',
        self::undo_config => 'undo_config',
        self::reset_config => 'reset_config',
        self::end_call => 'end_call',
        self::transfer_call => 'transfer_call',
        self::play_wav_files => 'play_wav_files',
        self::play_text => 'play_text',
        self::mute => 'mute',
        self::un_mute => 'un_mute',
        self::stop_all_control_messages => 'stop_all_control_messages',
        self::train_agent => 'train_agent',
        self::cancel_train_agent => 'cancel_train_agent',
        self::delete_session => 'delete_session',
        self::delete_all_contexts => 'delete_all_contexts',
        self::create_context => 'create_context',
        self::update_context => 'update_context',
        self::delete_context => 'delete_context',
        self::detect_intent => 'detect_intent',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

