<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/csi/conversation.proto

namespace Ondewo\Csi;

use UnexpectedValueException;

/**
 * Control message services.
 *
 * Protobuf type <code>ondewo.csi.ControlMessageServiceName</code>
 */
class ControlMessageServiceName
{
    /**
     * Unknown control message service name
     *
     * Generated from protobuf enum <code>UNKNOWNNAME = 0;</code>
     */
    const UNKNOWNNAME = 0;
    /**
     * Speech-2-Text control message service name
     *
     * Generated from protobuf enum <code>ondewo_s2t = 1;</code>
     */
    const ondewo_s2t = 1;
    /**
     * Text-2-Speech control message service name
     *
     * Generated from protobuf enum <code>ondewo_t2s = 2;</code>
     */
    const ondewo_t2s = 2;
    /**
     * NLU control message service name
     *
     * Generated from protobuf enum <code>ondewo_nlu = 3;</code>
     */
    const ondewo_nlu = 3;
    /**
     * SIP control message service name
     *
     * Generated from protobuf enum <code>ondewo_sip = 4;</code>
     */
    const ondewo_sip = 4;
    /**
     * VTSI control message service name
     *
     * Generated from protobuf enum <code>ondewo_vtsi = 5;</code>
     */
    const ondewo_vtsi = 5;
    /**
     * CSI control message service name
     *
     * Generated from protobuf enum <code>ondewo_csi = 6;</code>
     */
    const ondewo_csi = 6;
    /**
     * Survey control message service name
     *
     * Generated from protobuf enum <code>ondewo_survey = 7;</code>
     */
    const ondewo_survey = 7;

    private static $valueToName = [
        self::UNKNOWNNAME => 'UNKNOWNNAME',
        self::ondewo_s2t => 'ondewo_s2t',
        self::ondewo_t2s => 'ondewo_t2s',
        self::ondewo_nlu => 'ondewo_nlu',
        self::ondewo_sip => 'ondewo_sip',
        self::ondewo_vtsi => 'ondewo_vtsi',
        self::ondewo_csi => 'ondewo_csi',
        self::ondewo_survey => 'ondewo_survey',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

