<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/csi/conversation.proto

namespace Ondewo\Csi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The top-level message received from <code>ListS2sPipelines</code> endpoint.
 *
 * Generated from protobuf message <code>ondewo.csi.ListS2sPipelinesResponse</code>
 */
class ListS2sPipelinesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Collection of S2S pipelines of the server.
     *
     * Generated from protobuf field <code>repeated .ondewo.csi.S2sPipeline pipelines = 1;</code>
     */
    private $pipelines;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ondewo\Csi\S2sPipeline[] $pipelines
     *           Collection of S2S pipelines of the server.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Csi\Conversation::initOnce();
        parent::__construct($data);
    }

    /**
     * Collection of S2S pipelines of the server.
     *
     * Generated from protobuf field <code>repeated .ondewo.csi.S2sPipeline pipelines = 1;</code>
     * @return RepeatedField<\Ondewo\Csi\S2sPipeline>
     */
    public function getPipelines()
    {
        return $this->pipelines;
    }

    /**
     * Collection of S2S pipelines of the server.
     *
     * Generated from protobuf field <code>repeated .ondewo.csi.S2sPipeline pipelines = 1;</code>
     * @param \Ondewo\Csi\S2sPipeline[] $var
     * @return $this
     */
    public function setPipelines($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Ondewo\Csi\S2sPipeline::class);
        $this->pipelines = $arr;

        return $this;
    }

}

