<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/csi/conversation.proto

namespace Ondewo\Csi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The top-level message sent by client to <code>CreateS2sPipeline</code> and <code>UpdateS2sPipeline</code> endpoints and received from <code>GetS2sPipeline</code> endpoint.
 *
 * Generated from protobuf message <code>ondewo.csi.S2sPipeline</code>
 */
class S2sPipeline extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. CSI pipeline identifier consisting of S2T, NLU and T2S configuration. ID can be any non-empty string.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Required. S2T pipeline ID, e.g. "german_general"
     *
     * Generated from protobuf field <code>string s2t_pipeline_id = 2;</code>
     */
    protected $s2t_pipeline_id = '';
    /**
     * Required. NLU project ID, usually a hash, e.g. "ae33586b-x2s2-494a-aa73-1af0589cfc56".
     *
     * Generated from protobuf field <code>string nlu_project_id = 3;</code>
     */
    protected $nlu_project_id = '';
    /**
     * Required. Language code present in the corresponding NLU project, e.g. "de".
     *
     * Generated from protobuf field <code>string nlu_language_code = 4;</code>
     */
    protected $nlu_language_code = '';
    /**
     * Required. T2S pipeline ID, e.g. "kerstin".
     *
     * Generated from protobuf field <code>string t2s_pipeline_id = 5;</code>
     */
    protected $t2s_pipeline_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           Required. CSI pipeline identifier consisting of S2T, NLU and T2S configuration. ID can be any non-empty string.
     *     @type string $s2t_pipeline_id
     *           Required. S2T pipeline ID, e.g. "german_general"
     *     @type string $nlu_project_id
     *           Required. NLU project ID, usually a hash, e.g. "ae33586b-x2s2-494a-aa73-1af0589cfc56".
     *     @type string $nlu_language_code
     *           Required. Language code present in the corresponding NLU project, e.g. "de".
     *     @type string $t2s_pipeline_id
     *           Required. T2S pipeline ID, e.g. "kerstin".
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Csi\Conversation::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. CSI pipeline identifier consisting of S2T, NLU and T2S configuration. ID can be any non-empty string.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Required. CSI pipeline identifier consisting of S2T, NLU and T2S configuration. ID can be any non-empty string.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Required. S2T pipeline ID, e.g. "german_general"
     *
     * Generated from protobuf field <code>string s2t_pipeline_id = 2;</code>
     * @return string
     */
    public function getS2TPipelineId()
    {
        return $this->s2t_pipeline_id;
    }

    /**
     * Required. S2T pipeline ID, e.g. "german_general"
     *
     * Generated from protobuf field <code>string s2t_pipeline_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setS2TPipelineId($var)
    {
        GPBUtil::checkString($var, True);
        $this->s2t_pipeline_id = $var;

        return $this;
    }

    /**
     * Required. NLU project ID, usually a hash, e.g. "ae33586b-x2s2-494a-aa73-1af0589cfc56".
     *
     * Generated from protobuf field <code>string nlu_project_id = 3;</code>
     * @return string
     */
    public function getNluProjectId()
    {
        return $this->nlu_project_id;
    }

    /**
     * Required. NLU project ID, usually a hash, e.g. "ae33586b-x2s2-494a-aa73-1af0589cfc56".
     *
     * Generated from protobuf field <code>string nlu_project_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setNluProjectId($var)
    {
        GPBUtil::checkString($var, True);
        $this->nlu_project_id = $var;

        return $this;
    }

    /**
     * Required. Language code present in the corresponding NLU project, e.g. "de".
     *
     * Generated from protobuf field <code>string nlu_language_code = 4;</code>
     * @return string
     */
    public function getNluLanguageCode()
    {
        return $this->nlu_language_code;
    }

    /**
     * Required. Language code present in the corresponding NLU project, e.g. "de".
     *
     * Generated from protobuf field <code>string nlu_language_code = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setNluLanguageCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->nlu_language_code = $var;

        return $this;
    }

    /**
     * Required. T2S pipeline ID, e.g. "kerstin".
     *
     * Generated from protobuf field <code>string t2s_pipeline_id = 5;</code>
     * @return string
     */
    public function getT2SPipelineId()
    {
        return $this->t2s_pipeline_id;
    }

    /**
     * Required. T2S pipeline ID, e.g. "kerstin".
     *
     * Generated from protobuf field <code>string t2s_pipeline_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setT2SPipelineId($var)
    {
        GPBUtil::checkString($var, True);
        $this->t2s_pipeline_id = $var;

        return $this;
    }

}

