<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/csi/conversation.proto

namespace Ondewo\Csi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The top-level message sent by the client to the <code>S2sStream</code> method.
 * Multiple request messages should be sent in order:
 * <ul>
 *   <li>The first message must contain <code>pipeline_id</code> and can contain <code>session_id</code> or <code>initial_intent_display_name</code>. The message must not contain <code>audio</code> nor <code>end_of_stream</code>.</li>
 *   <li>All subsequent messages must contain <code>audio</code>. If <code>end_of_stream</code> is <code>true</code>, the stream is closed.</li>
 * </ul>
 *
 * Generated from protobuf message <code>ondewo.csi.S2sStreamRequest</code>
 */
class S2sStreamRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Optional. The CSI pipeline ID specified in the initial request.
     *
     * Generated from protobuf field <code>string pipeline_id = 1;</code>
     */
    protected $pipeline_id = '';
    /**
     * <p>Optional. The session or call ID specified in the initial request. It&apos;s up to the API caller to choose an appropriate string. It can be a random number or some type of user identifier (preferably hashed).</p>
     *
     * Generated from protobuf field <code>string session_id = 2;</code>
     */
    protected $session_id = '';
    /**
     * Optional. The input audio content to be recognized.
     *
     * Generated from protobuf field <code>bytes audio = 3;</code>
     */
    protected $audio = '';
    /**
     * If <code>true</code>, the recognizer will not return any further hypotheses about this piece of the audio. May only be populated for <code>event_type</code> = <code>RECOGNITION_EVENT_TRANSCRIPT</code>.
     *
     * Generated from protobuf field <code>bool end_of_stream = 4;</code>
     */
    protected $end_of_stream = false;
    /**
     * Optional. Intent display name to trigger in NLU system in the beginning of the conversation.
     *
     * Generated from protobuf field <code>string initial_intent_display_name = 5;</code>
     */
    protected $initial_intent_display_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $pipeline_id
     *           Optional. The CSI pipeline ID specified in the initial request.
     *     @type string $session_id
     *           <p>Optional. The session or call ID specified in the initial request. It&apos;s up to the API caller to choose an appropriate string. It can be a random number or some type of user identifier (preferably hashed).</p>
     *     @type string $audio
     *           Optional. The input audio content to be recognized.
     *     @type bool $end_of_stream
     *           If <code>true</code>, the recognizer will not return any further hypotheses about this piece of the audio. May only be populated for <code>event_type</code> = <code>RECOGNITION_EVENT_TRANSCRIPT</code>.
     *     @type string $initial_intent_display_name
     *           Optional. Intent display name to trigger in NLU system in the beginning of the conversation.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Csi\Conversation::initOnce();
        parent::__construct($data);
    }

    /**
     * Optional. The CSI pipeline ID specified in the initial request.
     *
     * Generated from protobuf field <code>string pipeline_id = 1;</code>
     * @return string
     */
    public function getPipelineId()
    {
        return $this->pipeline_id;
    }

    /**
     * Optional. The CSI pipeline ID specified in the initial request.
     *
     * Generated from protobuf field <code>string pipeline_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPipelineId($var)
    {
        GPBUtil::checkString($var, True);
        $this->pipeline_id = $var;

        return $this;
    }

    /**
     * <p>Optional. The session or call ID specified in the initial request. It&apos;s up to the API caller to choose an appropriate string. It can be a random number or some type of user identifier (preferably hashed).</p>
     *
     * Generated from protobuf field <code>string session_id = 2;</code>
     * @return string
     */
    public function getSessionId()
    {
        return $this->session_id;
    }

    /**
     * <p>Optional. The session or call ID specified in the initial request. It&apos;s up to the API caller to choose an appropriate string. It can be a random number or some type of user identifier (preferably hashed).</p>
     *
     * Generated from protobuf field <code>string session_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->session_id = $var;

        return $this;
    }

    /**
     * Optional. The input audio content to be recognized.
     *
     * Generated from protobuf field <code>bytes audio = 3;</code>
     * @return string
     */
    public function getAudio()
    {
        return $this->audio;
    }

    /**
     * Optional. The input audio content to be recognized.
     *
     * Generated from protobuf field <code>bytes audio = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAudio($var)
    {
        GPBUtil::checkString($var, False);
        $this->audio = $var;

        return $this;
    }

    /**
     * If <code>true</code>, the recognizer will not return any further hypotheses about this piece of the audio. May only be populated for <code>event_type</code> = <code>RECOGNITION_EVENT_TRANSCRIPT</code>.
     *
     * Generated from protobuf field <code>bool end_of_stream = 4;</code>
     * @return bool
     */
    public function getEndOfStream()
    {
        return $this->end_of_stream;
    }

    /**
     * If <code>true</code>, the recognizer will not return any further hypotheses about this piece of the audio. May only be populated for <code>event_type</code> = <code>RECOGNITION_EVENT_TRANSCRIPT</code>.
     *
     * Generated from protobuf field <code>bool end_of_stream = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setEndOfStream($var)
    {
        GPBUtil::checkBool($var);
        $this->end_of_stream = $var;

        return $this;
    }

    /**
     * Optional. Intent display name to trigger in NLU system in the beginning of the conversation.
     *
     * Generated from protobuf field <code>string initial_intent_display_name = 5;</code>
     * @return string
     */
    public function getInitialIntentDisplayName()
    {
        return $this->initial_intent_display_name;
    }

    /**
     * Optional. Intent display name to trigger in NLU system in the beginning of the conversation.
     *
     * Generated from protobuf field <code>string initial_intent_display_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setInitialIntentDisplayName($var)
    {
        GPBUtil::checkString($var, True);
        $this->initial_intent_display_name = $var;

        return $this;
    }

}

