<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/csi/conversation.proto

namespace Ondewo\Csi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The top-level message returned from the <code>S2sStream</code> method.
 * A response message is returned for each utterance of the input stream. It contains the full response from NLU system in <code>detect_intent_response</code> or the full T2S response in <code>synthesize_response</code>.
 * Multiple response messages can be returned in order:
 * <ul>
 *   <li>The first response message for an input utterance contains response from NLU system <code>detect_intent_response</code> with detected intent and N fulfillment messages (N &gt;= 0).</li>
 *   <li>The next N response messages contain for each fulfillment message one of the following:
 *     <ul>
 *       <li>T2S response <code>synthesize_response</code> with synthesized audio</li>
 *       <li>SIP trigger message <code>sip_trigger</code> with SIP trigger extracted from the fulfillment message</li>
 *     </ul>
 *   </li>
 * </ul>
 *
 * Generated from protobuf message <code>ondewo.csi.S2sStreamResponse</code>
 */
class S2sStreamResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Optional. Identifier of the utterance this response belongs to. All chunks of one synthesized utterance share the same <code>utterance_id</code>
     *
     * Generated from protobuf field <code>string utterance_id = 4;</code>
     */
    protected $utterance_id = '';
    /**
     * Optional. Zero-based index of this chunk within the utterance identified by <code>utterance_id</code>
     *
     * Generated from protobuf field <code>int32 chunk_index = 5;</code>
     */
    protected $chunk_index = 0;
    /**
     * Optional. If <code>true</code>, this is the last chunk of the utterance identified by <code>utterance_id</code>
     *
     * Generated from protobuf field <code>bool last_chunk = 6;</code>
     */
    protected $last_chunk = false;
    /**
     * Optional. Monotonic turn epoch of the conversation turn that produced this response. Used by consumers to fence stale audio of an interrupted turn
     *
     * Generated from protobuf field <code>uint64 turn_epoch = 7;</code>
     */
    protected $turn_epoch = 0;
    protected $response;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ondewo\Nlu\DetectIntentResponse $detect_intent_response
     *           full NLU detect intent response
     *     @type \Ondewo\T2s\SynthesizeResponse $synthesize_response
     *           full T2S synthesize response
     *     @type \Ondewo\Csi\SipTrigger $sip_trigger
     *           SIP trigger message
     *     @type string $utterance_id
     *           Optional. Identifier of the utterance this response belongs to. All chunks of one synthesized utterance share the same <code>utterance_id</code>
     *     @type int $chunk_index
     *           Optional. Zero-based index of this chunk within the utterance identified by <code>utterance_id</code>
     *     @type bool $last_chunk
     *           Optional. If <code>true</code>, this is the last chunk of the utterance identified by <code>utterance_id</code>
     *     @type int|string $turn_epoch
     *           Optional. Monotonic turn epoch of the conversation turn that produced this response. Used by consumers to fence stale audio of an interrupted turn
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Csi\Conversation::initOnce();
        parent::__construct($data);
    }

    /**
     * full NLU detect intent response
     *
     * Generated from protobuf field <code>.ondewo.nlu.DetectIntentResponse detect_intent_response = 1;</code>
     * @return \Ondewo\Nlu\DetectIntentResponse|null
     */
    public function getDetectIntentResponse()
    {
        return $this->readOneof(1);
    }

    public function hasDetectIntentResponse()
    {
        return $this->hasOneof(1);
    }

    /**
     * full NLU detect intent response
     *
     * Generated from protobuf field <code>.ondewo.nlu.DetectIntentResponse detect_intent_response = 1;</code>
     * @param \Ondewo\Nlu\DetectIntentResponse $var
     * @return $this
     */
    public function setDetectIntentResponse($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Nlu\DetectIntentResponse::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * full T2S synthesize response
     *
     * Generated from protobuf field <code>.ondewo.t2s.SynthesizeResponse synthesize_response = 2;</code>
     * @return \Ondewo\T2s\SynthesizeResponse|null
     */
    public function getSynthesizeResponse()
    {
        return $this->readOneof(2);
    }

    public function hasSynthesizeResponse()
    {
        return $this->hasOneof(2);
    }

    /**
     * full T2S synthesize response
     *
     * Generated from protobuf field <code>.ondewo.t2s.SynthesizeResponse synthesize_response = 2;</code>
     * @param \Ondewo\T2s\SynthesizeResponse $var
     * @return $this
     */
    public function setSynthesizeResponse($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\T2s\SynthesizeResponse::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * SIP trigger message
     *
     * Generated from protobuf field <code>.ondewo.csi.SipTrigger sip_trigger = 3;</code>
     * @return \Ondewo\Csi\SipTrigger|null
     */
    public function getSipTrigger()
    {
        return $this->readOneof(3);
    }

    public function hasSipTrigger()
    {
        return $this->hasOneof(3);
    }

    /**
     * SIP trigger message
     *
     * Generated from protobuf field <code>.ondewo.csi.SipTrigger sip_trigger = 3;</code>
     * @param \Ondewo\Csi\SipTrigger $var
     * @return $this
     */
    public function setSipTrigger($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Csi\SipTrigger::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Optional. Identifier of the utterance this response belongs to. All chunks of one synthesized utterance share the same <code>utterance_id</code>
     *
     * Generated from protobuf field <code>string utterance_id = 4;</code>
     * @return string
     */
    public function getUtteranceId()
    {
        return $this->utterance_id;
    }

    /**
     * Optional. Identifier of the utterance this response belongs to. All chunks of one synthesized utterance share the same <code>utterance_id</code>
     *
     * Generated from protobuf field <code>string utterance_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUtteranceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->utterance_id = $var;

        return $this;
    }

    /**
     * Optional. Zero-based index of this chunk within the utterance identified by <code>utterance_id</code>
     *
     * Generated from protobuf field <code>int32 chunk_index = 5;</code>
     * @return int
     */
    public function getChunkIndex()
    {
        return $this->chunk_index;
    }

    /**
     * Optional. Zero-based index of this chunk within the utterance identified by <code>utterance_id</code>
     *
     * Generated from protobuf field <code>int32 chunk_index = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setChunkIndex($var)
    {
        GPBUtil::checkInt32($var);
        $this->chunk_index = $var;

        return $this;
    }

    /**
     * Optional. If <code>true</code>, this is the last chunk of the utterance identified by <code>utterance_id</code>
     *
     * Generated from protobuf field <code>bool last_chunk = 6;</code>
     * @return bool
     */
    public function getLastChunk()
    {
        return $this->last_chunk;
    }

    /**
     * Optional. If <code>true</code>, this is the last chunk of the utterance identified by <code>utterance_id</code>
     *
     * Generated from protobuf field <code>bool last_chunk = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setLastChunk($var)
    {
        GPBUtil::checkBool($var);
        $this->last_chunk = $var;

        return $this;
    }

    /**
     * Optional. Monotonic turn epoch of the conversation turn that produced this response. Used by consumers to fence stale audio of an interrupted turn
     *
     * Generated from protobuf field <code>uint64 turn_epoch = 7;</code>
     * @return int|string
     */
    public function getTurnEpoch()
    {
        return $this->turn_epoch;
    }

    /**
     * Optional. Monotonic turn epoch of the conversation turn that produced this response. Used by consumers to fence stale audio of an interrupted turn
     *
     * Generated from protobuf field <code>uint64 turn_epoch = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTurnEpoch($var)
    {
        GPBUtil::checkUint64($var);
        $this->turn_epoch = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getResponse()
    {
        return $this->whichOneof("response");
    }

}

