<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/csi/conversation.proto

namespace Ondewo\Csi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Request to set control status.
 *
 * Generated from protobuf message <code>ondewo.csi.SetControlStatusRequest</code>
 */
class SetControlStatusRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Control status
     *
     * Generated from protobuf field <code>.ondewo.csi.ControlStatus control_status = 1;</code>
     */
    protected $control_status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $control_status
     *           Control status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Csi\Conversation::initOnce();
        parent::__construct($data);
    }

    /**
     * Control status
     *
     * Generated from protobuf field <code>.ondewo.csi.ControlStatus control_status = 1;</code>
     * @return int
     */
    public function getControlStatus()
    {
        return $this->control_status;
    }

    /**
     * Control status
     *
     * Generated from protobuf field <code>.ondewo.csi.ControlStatus control_status = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setControlStatus($var)
    {
        GPBUtil::checkEnum($var, \Ondewo\Csi\ControlStatus::class);
        $this->control_status = $var;

        return $this;
    }

}

