<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/csi/conversation.proto

namespace Ondewo\Csi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * <p>Response of <code>SetCallMediaControl</code>.</p>
 *
 * Generated from protobuf message <code>ondewo.csi.SetCallMediaControlResponse</code>
 */
class SetCallMediaControlResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <p>The level the server holds after this request.</p>
     *
     * Generated from protobuf field <code>.ondewo.csi.CallMediaControlLevel applied = 1;</code>
     */
    protected $applied = null;
    /**
     * <p><code>true</code> if the effective level changed.</p>
     *
     * Generated from protobuf field <code>bool changed = 2;</code>
     */
    protected $changed = false;
    /**
     * <p><code>true</code> if the request's generation was not greater than the last applied generation. The
     * request was ignored.</p>
     *
     * Generated from protobuf field <code>bool stale = 3;</code>
     */
    protected $stale = false;
    /**
     * <p><code>true</code> while an utterance is still draining to the caller.</p>
     *
     * Generated from protobuf field <code>bool bot_playback_in_flight = 4;</code>
     */
    protected $bot_playback_in_flight = false;
    /**
     * <p>Empty when the level was applied. Otherwise a stable refusal token: <code>amd-in-progress</code>
     * (<code>listening_paused</code> refused during the answering-machine-detection window).</p>
     *
     * Generated from protobuf field <code>string refusal_reason = 5;</code>
     */
    protected $refusal_reason = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ondewo\Csi\CallMediaControlLevel $applied
     *           <p>The level the server holds after this request.</p>
     *     @type bool $changed
     *           <p><code>true</code> if the effective level changed.</p>
     *     @type bool $stale
     *           <p><code>true</code> if the request's generation was not greater than the last applied generation. The
     *           request was ignored.</p>
     *     @type bool $bot_playback_in_flight
     *           <p><code>true</code> while an utterance is still draining to the caller.</p>
     *     @type string $refusal_reason
     *           <p>Empty when the level was applied. Otherwise a stable refusal token: <code>amd-in-progress</code>
     *           (<code>listening_paused</code> refused during the answering-machine-detection window).</p>
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Csi\Conversation::initOnce();
        parent::__construct($data);
    }

    /**
     * <p>The level the server holds after this request.</p>
     *
     * Generated from protobuf field <code>.ondewo.csi.CallMediaControlLevel applied = 1;</code>
     * @return \Ondewo\Csi\CallMediaControlLevel|null
     */
    public function getApplied()
    {
        return $this->applied;
    }

    public function hasApplied()
    {
        return isset($this->applied);
    }

    public function clearApplied()
    {
        unset($this->applied);
    }

    /**
     * <p>The level the server holds after this request.</p>
     *
     * Generated from protobuf field <code>.ondewo.csi.CallMediaControlLevel applied = 1;</code>
     * @param \Ondewo\Csi\CallMediaControlLevel $var
     * @return $this
     */
    public function setApplied($var)
    {
        GPBUtil::checkMessage($var, \Ondewo\Csi\CallMediaControlLevel::class);
        $this->applied = $var;

        return $this;
    }

    /**
     * <p><code>true</code> if the effective level changed.</p>
     *
     * Generated from protobuf field <code>bool changed = 2;</code>
     * @return bool
     */
    public function getChanged()
    {
        return $this->changed;
    }

    /**
     * <p><code>true</code> if the effective level changed.</p>
     *
     * Generated from protobuf field <code>bool changed = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setChanged($var)
    {
        GPBUtil::checkBool($var);
        $this->changed = $var;

        return $this;
    }

    /**
     * <p><code>true</code> if the request's generation was not greater than the last applied generation. The
     * request was ignored.</p>
     *
     * Generated from protobuf field <code>bool stale = 3;</code>
     * @return bool
     */
    public function getStale()
    {
        return $this->stale;
    }

    /**
     * <p><code>true</code> if the request's generation was not greater than the last applied generation. The
     * request was ignored.</p>
     *
     * Generated from protobuf field <code>bool stale = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setStale($var)
    {
        GPBUtil::checkBool($var);
        $this->stale = $var;

        return $this;
    }

    /**
     * <p><code>true</code> while an utterance is still draining to the caller.</p>
     *
     * Generated from protobuf field <code>bool bot_playback_in_flight = 4;</code>
     * @return bool
     */
    public function getBotPlaybackInFlight()
    {
        return $this->bot_playback_in_flight;
    }

    /**
     * <p><code>true</code> while an utterance is still draining to the caller.</p>
     *
     * Generated from protobuf field <code>bool bot_playback_in_flight = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setBotPlaybackInFlight($var)
    {
        GPBUtil::checkBool($var);
        $this->bot_playback_in_flight = $var;

        return $this;
    }

    /**
     * <p>Empty when the level was applied. Otherwise a stable refusal token: <code>amd-in-progress</code>
     * (<code>listening_paused</code> refused during the answering-machine-detection window).</p>
     *
     * Generated from protobuf field <code>string refusal_reason = 5;</code>
     * @return string
     */
    public function getRefusalReason()
    {
        return $this->refusal_reason;
    }

    /**
     * <p>Empty when the level was applied. Otherwise a stable refusal token: <code>amd-in-progress</code>
     * (<code>listening_paused</code> refused during the answering-machine-detection window).</p>
     *
     * Generated from protobuf field <code>string refusal_reason = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setRefusalReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->refusal_reason = $var;

        return $this;
    }

}

