<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/csi/conversation.proto

namespace Ondewo\Csi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Response of setting the control status with the old and new status objects.
 *
 * Generated from protobuf message <code>ondewo.csi.SetControlStatusResponse</code>
 */
class SetControlStatusResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Previous 'old' control status
     *
     * Generated from protobuf field <code>.ondewo.csi.ControlStatus old_control_status = 1;</code>
     */
    protected $old_control_status = 0;
    /**
     * Current 'new' control status
     *
     * Generated from protobuf field <code>.ondewo.csi.ControlStatus new_control_status = 2;</code>
     */
    protected $new_control_status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $old_control_status
     *           Previous 'old' control status
     *     @type int $new_control_status
     *           Current 'new' control status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Csi\Conversation::initOnce();
        parent::__construct($data);
    }

    /**
     * Previous 'old' control status
     *
     * Generated from protobuf field <code>.ondewo.csi.ControlStatus old_control_status = 1;</code>
     * @return int
     */
    public function getOldControlStatus()
    {
        return $this->old_control_status;
    }

    /**
     * Previous 'old' control status
     *
     * Generated from protobuf field <code>.ondewo.csi.ControlStatus old_control_status = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setOldControlStatus($var)
    {
        GPBUtil::checkEnum($var, \Ondewo\Csi\ControlStatus::class);
        $this->old_control_status = $var;

        return $this;
    }

    /**
     * Current 'new' control status
     *
     * Generated from protobuf field <code>.ondewo.csi.ControlStatus new_control_status = 2;</code>
     * @return int
     */
    public function getNewControlStatus()
    {
        return $this->new_control_status;
    }

    /**
     * Current 'new' control status
     *
     * Generated from protobuf field <code>.ondewo.csi.ControlStatus new_control_status = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setNewControlStatus($var)
    {
        GPBUtil::checkEnum($var, \Ondewo\Csi\ControlStatus::class);
        $this->new_control_status = $var;

        return $this;
    }

}

