<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ondewo/csi/conversation.proto

namespace Ondewo\Csi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * SIP trigger message.
 *
 * Generated from protobuf message <code>ondewo.csi.SipTrigger</code>
 */
class SipTrigger extends \Google\Protobuf\Internal\Message
{
    /**
     * Type of the SIP trigger.
     *
     * Generated from protobuf field <code>.ondewo.csi.SipTrigger.SipTriggerType type = 1;</code>
     */
    protected $type = 0;
    /**
     * extra parameters for the trigger
     *
     * Generated from protobuf field <code>.google.protobuf.Struct content = 2;</code>
     */
    protected $content = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *           Type of the SIP trigger.
     *     @type \Google\Protobuf\Struct $content
     *           extra parameters for the trigger
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ondewo\Csi\Conversation::initOnce();
        parent::__construct($data);
    }

    /**
     * Type of the SIP trigger.
     *
     * Generated from protobuf field <code>.ondewo.csi.SipTrigger.SipTriggerType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Type of the SIP trigger.
     *
     * Generated from protobuf field <code>.ondewo.csi.SipTrigger.SipTriggerType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Ondewo\Csi\SipTrigger\SipTriggerType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * extra parameters for the trigger
     *
     * Generated from protobuf field <code>.google.protobuf.Struct content = 2;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getContent()
    {
        return $this->content;
    }

    public function hasContent()
    {
        return isset($this->content);
    }

    public function clearContent()
    {
        unset($this->content);
    }

    /**
     * extra parameters for the trigger
     *
     * Generated from protobuf field <code>.google.protobuf.Struct content = 2;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->content = $var;

        return $this;
    }

}

